### ISSUE TITLE
Connection was closed

### ISSUE THREAD

**Issue by awdr74100** [MTKruto/MTKruto#205] opened 2024-03-29 12:29 UTC
```text
macos: v14.4.1
node: v20.12.0
pnpm:  v8.15.5
```

```ts
import { Client } from "@mtkruto/node";
import input from "@inquirer/input";

async function init() {
  /* I'm sure the parameters are set correctly. */
  const apiId = "00000000";
  const apiHash = "0000000000000000000000000000000000";

  const client = new Client(null, +apiId, apiHash);

  await client.start({
    phone: () => input({ message: "Enter your phone number:" }),
    code: () => input({ message: "Enter the code you received:" }),
    password: () => input({ message: "Enter your account's password:" }),
  });

  console.log("Started");
}

init().catch((error) => {
  console.log(error);
});
```
<img width="1079" alt="截圖 2024-03-29 晚上8 19 57" src="https://github.com/MTKruto/MTKruto/assets/47501692/dc4828a1-cba2-446a-8a9f-3bafa8c8bcbf">

I would like to ask if I have done any step wrong? This error does not occur with gramjs.

I would also like to ask if the only difference between this library and gramjs is deno compatibility? Is there any difference in performance?

**Comment by roj1512** [comment] 2024-03-29 12:35
I’m unable to reproduce this issue. Can you send the logs with LOG_VERBOSITY=10 to [@MTKrutoBot](https://t.me/MTKrutoBot)?

> I would also like to ask if the only difference between this library and gramjs is deno compatibility?

No, they are completely different in many aspects.

> Is there any difference in performance?

While I don’t have done any benchmarks, I can’t say which one performs better. Apparently tho, I don’t think there is a significant performance gap.

**Comment by roj1512** [comment] 2024-03-30 13:52
Fixed by https://github.com/MTKruto/MTKruto/commit/ef7a70ff254373ebe050e9c87d0271e889bc107c. Upgrading to 0.1.191 should fix it.

**Closed by roj1512** 2024-03-30 13:52 UTC
